"""initial_migration

Revision ID: 34c1abc4c157
Revises: cabcbd0d8153
Create Date: 2024-05-13 22:28:39.584030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34c1abc4c157'
down_revision = 'cabcbd0d8153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tasks_task_author_id_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['task_author_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_task_author_id_fkey', 'tasks', 'users', ['task_author_id'], ['id'])
    # ### end Alembic commands ###
